kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.5.0
        args:
          - '--storage.tsdb.retention=12h'
          - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
        - name: ui
          containerPort: 9090
        resources:
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-configuration
